apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "9101"
    prometheus.io/scrape: "true"
  labels:
    app: haproxy-exporter
  name: haproxy-exporter
spec:
  ports:
  - name: 9101-tcp
    port: 9101
    protocol: TCP
    targetPort: 9101
  selector:
    app: haproxy-exporter
  sessionAffinity: None
  type: ClusterIP
