apiVersion: v1
kind: DeploymentConfig
metadata:
  name: kube-state-metrics
  # namespace: monitoring
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kube-state-metrics
        version: "v0.3.0"
    spec:
      nodeSelector: {"region":"infra"}
      containers:
      - name: kube-state-metrics
        image: REGISTRY-IP/openshift/kube-state-metrics:IMAGE-TAG
        ports:
        - containerPort: 8080
