apiVersion: v1
kind: List
metadata:
  resourceVersion: "1"
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: grafana-ocp
  spec:
    tags:
      - name: latest
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: prometheus-node-exporter
  spec:
    tags:
      - name: latest
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: kube-state-metrics
  spec:
    tags:
      - name: latest
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: haproxy-exporter
  spec:
    tags:
      - name: latest
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: blackbox-exporter
  spec:
    tags:
      - name: latest
