{
 "title": "Cluster",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total Pods",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=~\".*\"})",
     "legendFormat": "Pods"
    }
   ]
  },
  {
   "title": "Running Pods",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Running\"})",
     "legendFormat": "Pods"
    }
   ]
  },
  {
   "title": "Failed Pods",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase!~\"Running|Succeeded|\"})",
     "legendFormat": "Pods"
    }
   ]
  },
  {
   "title": "Completed Build Pod",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Succeeded\"})",
     "legendFormat": "Pods"
    }
   ]
  },
  {
   "title": "Total Projects",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "count(kube_namespace_created)", "legendFormat": "Pods" }
   ]
  },
  {
   "title": "Changes in the cluster",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(changes(kubelet_running_container_count[10m]))",
     "legendFormat": "POD Change"
    }
   ]
  },
  {
   "title": "API Calls",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (apiserver_request_count{verb=~\"POST|PUT|DELETE|PATCH\"})",
     "legendFormat": "API calls (Update) {{instance}}"
    },
    {
     "expr": "sum by (instance) (apiserver_request_count{verb=~\"GET|LIST|WATCH\"})",
     "legendFormat": "API calls (View) {{instance}}"
    },
    {
     "expr": "sum by (instance) (apiserver_request_count)",
     "legendFormat": "Total Calls {{instance}}"
    }
   ]
  },
  {
   "title": "Total Cluster Memory Used by Pods",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes) / sum(kube_node_status_capacity_memory_bytes)",
     "legendFormat": "Memory %"
    }
   ]
  },
  {
   "title": "CPU core usage by Project",
   "type": "graph",
   "description": "milicore, 1core = 1000m-core",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (kube_pod_container_resource_requests_cpu_cores) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Memory usage by Project",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (kube_pod_container_resource_requests_memory_bytes) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  }
 ]
}