{
 "title": "Master-API",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total API Calls",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_count[10m]))",
     "legendFormat": "Number of API calls"
    }
   ]
  },
  {
   "title": "API Calls (View)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_count{verb=~\"GET|LIST|WATCH\"}[5m])) by (instance)",
     "legendFormat": "API calls (View) {{instance}}"
    }
   ]
  },
  {
   "title": "API Calls (Update)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_count{verb=~\"POST|PUT|DELETE|PATCH\"}[5m])) by (instance)",
     "legendFormat": "API calls (Update) {{instance}}"
    }
   ]
  }
 ]
}